entities:
- Product:
    doc: Ini product
    author: bhangun
    example: 
    properties:
    - code: String, min=3, max=30, required //Product code 
    - name: String, max=30 
    - sku: int,min=3, max=30, required
    - unit: enum=Unit
    - status: Status, manyToOne

- Status:
   properties:
   - name: String, max=30

- History:
    properties:
    - payload: String

enums:
 - Unit:
    - Kg
    - g
  