info:
  name: golokApps
  title: Contoh1
  description: Ini contoh aplikasi
endpoint:
  url: http://localhost
applications:
  frontend:
    appsName: my_golok_front
    framework: flutter
    packageName: tech.kays
    localDatabase: hive
    admin: true
    themes: default
    plugins:
      - connection
    stateManagement: riverpod
    platform:
      - web
      - android
      - linux
      - ios
      - desktop
    locale: en, id
    entities:
      - Product
      - Order
      - OrderLine
entities:
  - name: Product
    properties:
      - origin: double
        type: double
        dartType: double
        dartTypeCapital: Double
        dartTypeSnake: double
      - origin: String
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: String
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: User
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: datetime
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: datetime
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: string
        type: String
        dartType: String
        dartTypeCapital: String
        dartTypeSnake: String
      - origin: string
        type: String
        dartType: String
        dartTypeCapital: String
        dartTypeSnake: String
      - origin: int
        type: int
        dartType: int
        dartTypeCapital: Int
        dartTypeSnake: int
      - origin: Brand
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: Category
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: User
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: Status
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: Unit
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
    nameClass: Product
    nameField: product
    nameFile: product
  - name: Inventory
    properties:
      - origin: double
        type: double
        dartType: double
        dartTypeCapital: Double
        dartTypeSnake: double
      - origin: String
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: String
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: User
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: datetime
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: datetime
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: int
        type: int
        dartType: int
        dartTypeCapital: Int
        dartTypeSnake: int
      - origin: int
        type: int
        dartType: int
        dartTypeCapital: Int
        dartTypeSnake: int
      - origin: int
        type: int
        dartType: int
        dartTypeCapital: Int
        dartTypeSnake: int
      - origin: Status
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: Product
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: date
        type: DateTime
        dartType: DateTime
        dartTypeCapital: DateTime
        dartTypeSnake: DateTime
      - origin: Warehouse
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
    nameClass: Inventory
    nameField: inventory
    nameFile: inventory
  - name: Price
    properties:
      - origin: double
        type: double
        dartType: double
        dartTypeCapital: Double
        dartTypeSnake: double
      - origin: String
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: String
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: User
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: datetime
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: datetime
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: double
        type: double
        dartType: double
        dartTypeCapital: Double
        dartTypeSnake: double
    nameClass: Price
    nameField: price
    nameFile: price
  - name: Invoice
    properties:
      - origin: double
        type: double
        dartType: double
        dartTypeCapital: Double
        dartTypeSnake: double
      - origin: String
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: String
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: User
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: datetime
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: datetime
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: Order
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: Status
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
    nameClass: Invoice
    nameField: invoice
    nameFile: invoice
  - name: Status
    properties:
      - origin: double
        type: double
        dartType: double
        dartTypeCapital: Double
        dartTypeSnake: double
      - origin: String
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: String
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: User
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: datetime
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: datetime
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: Category
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
    nameClass: Status
    nameField: status
    nameFile: status
  - name: Category
    properties: []
    nameClass: Category
    nameField: category
    nameFile: category
  - name: ""
    properties: []
    nameClass: ""
    nameField: ""
    nameFile: ""
  - name: Warehouse
    properties:
      - origin: double
        type: double
        dartType: double
        dartTypeCapital: Double
        dartTypeSnake: double
      - origin: String
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: String
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: User
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: datetime
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: datetime
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: Status
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
    nameClass: Warehouse
    nameField: warehouse
    nameFile: warehouse
  - name: User
    properties:
      - origin: double
        type: double
        dartType: double
        dartTypeCapital: Double
        dartTypeSnake: double
      - origin: String
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: String
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: User
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: datetime
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: datetime
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
    nameClass: User
    nameField: user
    nameFile: user
  - name: Order
    properties:
      - origin: double
        type: double
        dartType: double
        dartTypeCapital: Double
        dartTypeSnake: double
      - origin: String
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: String
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: User
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: datetime
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: datetime
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: Product
        type: ""
        dartType: ""
        dartTypeCapital: ""
        dartTypeSnake: ""
      - origin: int
        type: int
        dartType: int
        dartTypeCapital: Int
        dartTypeSnake: int
      - origin: double
        type: double
        dartType: double
        dartTypeCapital: Double
        dartTypeSnake: double
    nameClass: Order
    nameField: order
    nameFile: order
golokConfiguration:
  default:
    - name: default
      properties:
        - id: double
        - name: String, max=100
        - description: String, max=200
        - createdBy: User
        - createAt: datetime
        - updateAt: datetime
User&NoneDefault:
  - employee: Employee, min=3, max=20
  - username: null
  - password: null
  - email: null
  - active: null
  - enable: null
employee: Employee, min=3, max=20
enums: []
